In [14]:
from sklearn.datasets import load_diabetes

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [15]:
X, y = load_diabetes(return_X_y=True)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [17]:
lr =LinearRegression()
lr.fit(X_train,y_train)
lr.intercept_, lr.coef_

(151.88331005254167,
 array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
        -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
         861.12700152,   52.42112238]))

In [18]:
y_pred = lr.predict(X_test)
r2_score(y_test,y_pred)

0.4399338661568968

In [19]:
from sklearn.linear_model import SGDRegressor
import random

In [20]:
miniSgd = SGDRegressor(learning_rate='constant',eta0=0.1)

In [21]:
batch_size = 35
epochs = 100


for i in range(epochs):
    # select randomly batch size number from total number of rows
    idx = random.sample(range(X_train.shape[0]), batch_size)
    miniSgd.partial_fit(X_train[idx],y_train[idx])

In [22]:
miniSgd.intercept_, miniSgd.coef_

(array([148.73682354]),
 array([  63.78182344,  -59.1745448 ,  347.70759655,  257.54259501,
          15.27926155,  -36.99553247, -165.59572372,  120.54163875,
         323.91741275,  118.27602053]))

In [23]:
y_pred = miniSgd.predict(X_test)

In [24]:
r2_score(y_test,y_pred)

0.42729251735413754