In [81]:
import numpy as np
import pandas as pd


In [82]:
df = pd.read_csv('train.csv')
df = df.drop(columns=['PassengerId','Name','Ticket','Cabin'])
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [83]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=0)

In [84]:
X_train

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
140       3  female   NaN      0      2  15.2458        C
439       2    male  31.0      0      0  10.5000        S
817       2    male  31.0      1      1  37.0042        C
378       3    male  20.0      0      0   4.0125        C
491       3    male  21.0      0      0   7.2500        S
..      ...     ...   ...    ...    ...      ...      ...
835       1  female  39.0      1      1  83.1583        C
192       3  female  19.0      1      0   7.8542        S
629       3    male   NaN      0      0   7.7333        Q
559       3  female  36.0      1      0  17.4000        S
684       2    male  60.0      1      1  39.0000        S

[712 rows x 7 columns]

# check null

In [85]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [86]:
from sklearn.impute import SimpleImputer

si = SimpleImputer()
si_cat = SimpleImputer(strategy='most_frequent')

X_train_age = si.fit_transform(X_train[['Age']])
X_test_age = si.transform(X_test[['Age']])

X_train_embarked = si_cat.fit_transform(X_train[['Embarked']])
X_test_embarked = si_cat.transform(X_test[['Embarked']])

In [87]:
pd.DataFrame(X_train_age).isnull().sum()
pd.DataFrame(X_train_embarked).isnull().sum()

0    0
dtype: int64

# num data -> standarization

In [88]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

In [89]:
X_train_fair = ss.fit_transform(X_train[['Fare']])
X_test_fair = ss.transform(X_test[['Fare']])

X_train_age = ss.fit_transform(X_train_age)
X_test_age = ss.transform(X_test_age)

In [90]:
X_train_fair

array([[-3.31679043e-01],
       [-4.26405420e-01],
       [ 1.02619579e-01],
       [-5.55896206e-01],
       [-4.91275564e-01],
       [-6.71246274e-02],
       [-4.75307528e-01],
       [-4.78716704e-01],
       [-6.35985883e-01],
       [-4.80796540e-01],
       [-3.71845613e-02],
       [-4.39878450e-01],
       [ 4.01936408e-01],
       [-4.91774565e-01],
       [-4.81545042e-01],
       [-4.81295542e-01],
       [ 6.01121680e-01],
       [-4.75307528e-01],
       [-4.13764725e-01],
       [-1.06046713e-01],
       [-6.35985883e-01],
       [-4.75307528e-01],
       [-3.47479414e-01],
       [-4.26405420e-01],
       [-4.11601056e-01],
       [-4.75307528e-01],
       [-1.56944826e-01],
       [-2.76705090e-01],
       [-4.69070015e-01],
       [-4.81628874e-01],
       [-4.75307528e-01],
       [-4.95267572e-01],
       [ 7.25956810e-02],
       [ 1.56178366e-01],
       [-3.31679043e-01],
       [-3.90976342e-01],
       [-4.78385367e-01],
       [-3.57713902e-02],
       [-2.2

In [91]:
X_train_age

array([[ 0.        ],
       [ 0.09593203],
       [ 0.09593203],
       [-0.74502968],
       [-0.66857861],
       [ 1.20447245],
       [-0.59212755],
       [ 0.        ],
       [ 0.        ],
       [-0.28632329],
       [-0.36277436],
       [-0.66857861],
       [ 0.09593203],
       [-1.127285  ],
       [ 0.        ],
       [ 0.        ],
       [ 2.6952682 ],
       [ 0.        ],
       [-2.19759989],
       [ 0.32528522],
       [ 1.47205118],
       [-0.8979318 ],
       [ 0.        ],
       [ 3.07752352],
       [-1.20373606],
       [-0.82148074],
       [ 0.01948096],
       [ 0.09593203],
       [ 0.17238309],
       [-1.05083393],
       [ 1.54850224],
       [-0.43922542],
       [ 2.00720863],
       [-1.73889351],
       [-1.58599138],
       [ 0.24883415],
       [-0.82148074],
       [ 0.21060862],
       [-2.19759989],
       [ 1.16624692],
       [ 0.        ],
       [-0.82148074],
       [-0.66857861],
       [-1.9682467 ],
       [-0.13342117],
       [-0

# cat-> Encoding (Ordinal or onehot)

In [92]:
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [93]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False,drop='first',handle_unknown='ignore')

X_train_sex = ohe.fit_transform(X_train[['Sex']])
X_test_sex = ohe.transform(X_test[['Sex']])

X_train_embarked = ohe.fit_transform(X_train_embarked)
X_test_embarked = ohe.transform(X_test_embarked)

C:\Users\HP TECHNOLOGY\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\HP TECHNOLOGY\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [94]:
X_train_sex

array([[0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],

In [95]:
train_rest = X_train[['Pclass','SibSp','Parch']]
test_rest = X_test[['Pclass','SibSp','Parch']]
train_rest


Pclass  SibSp  Parch
140       3      0      2
439       2      0      0
817       2      1      1
378       3      0      0
491       3      0      0
..      ...    ...    ...
835       1      1      1
192       3      1      0
629       3      0      0
559       3      1      0
684       2      1      1

[712 rows x 3 columns]

In [96]:
print(train_rest.shape)
print(X_train_sex.shape)
print(X_train_age.shape)
print(X_train_embarked.shape)
print(X_train_fair.shape)

(712, 3)
(712, 1)
(712, 1)
(712, 2)
(712, 1)


In [97]:
X_train_trf = np.concatenate((X_train_age,X_train_sex,X_train_embarked,X_train_fair,train_rest),axis=1)
X_test_trf = np.concatenate((X_test_age,X_test_sex,X_test_embarked,X_test_fair,test_rest),axis=1)

In [98]:
X_train_trf

array([[0.        , 0.        , 0.        , ..., 3.        , 0.        ,
        2.        ],
       [0.09593203, 1.        , 0.        , ..., 2.        , 0.        ,
        0.        ],
       [0.09593203, 1.        , 0.        , ..., 2.        , 1.        ,
        1.        ],
       ...,
       [0.        , 1.        , 1.        , ..., 3.        , 0.        ,
        0.        ],
       [0.47818735, 0.        , 0.        , ..., 3.        , 1.        ,
        0.        ],
       [2.31301288, 1.        , 0.        , ..., 2.        , 1.        ,
        1.        ]])

In [99]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
dtc = DecisionTreeClassifier()

In [100]:
dtc.fit(X_train_trf,y_train)
y_pred = dtc.predict(X_test_trf)
accuracy_score(y_test,y_pred)

0.7821229050279329