In [25]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

In [26]:
df = pd.read_csv('heart.csv')
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [27]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [28]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((820, 13), (205, 13), (820,), (205,))

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [30]:
clf_lr = LogisticRegression()
clf_dt = DecisionTreeClassifier()
clf_rf = RandomForestClassifier()

In [31]:
clf_lr.fit(X_train,y_train)
clf_dt.fit(X_train,y_train)
clf_rf.fit(X_train,y_train)

C:\Users\HP TECHNOLOGY\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


RandomForestClassifier()

In [32]:
y_pred_lr = clf_lr.predict(X_test)
y_pred_dt = clf_dt.predict(X_test)
y_pred_rf = clf_rf.predict(X_test)

In [33]:
from sklearn.metrics import accuracy_score, confusion_matrix

# Accuracy Score

In [34]:
print("Accuracy Score of Logistic Regression",accuracy_score(y_test,y_pred_lr))
print("Accuracy Score of Decision Tree",accuracy_score(y_test,y_pred_dt))
print("Accuracy Score of Random Forrest",accuracy_score(y_test,y_pred_rf))

Accuracy Score of Logistic Regression 0.8390243902439024
Accuracy Score of Decision Tree 0.9804878048780488
Accuracy Score of Random Forrest 1.0


# Confusion Matrix
![A descriptive alt text](confusion_matrix.png)

In [35]:
print("Confusion matrix of Logistic Regression\n"),
pd.DataFrame(confusion_matrix(y_test,y_pred_lr))

Confusion matrix of Logistic Regression



0   1
0  82  23
1  10  90

In [36]:
print("Confusion matrix of Decision Tree")
pd.DataFrame(confusion_matrix(y_test,y_pred_dt))

Confusion matrix of Decision Tree


0    1
0  101    4
1    0  100

In [37]:
print("Confusion matrix of Random Forrest\n")
pd.DataFrame(confusion_matrix(y_test,y_pred_rf))

Confusion matrix of Random Forrest



0    1
0  105    0
1    0  100

In [38]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Precision, Recall Score, F1 score
![A descriptive alt text](pre,recall,f1.png)

In [39]:
print("Precision of Logistic Regression:",precision_score(y_test,y_pred_lr))
print("Recall of Logistic Regression:",recall_score(y_test,y_pred_lr))
print("F1 score of Logistic Regression:",f1_score(y_test,y_pred_lr))

Precision of Logistic Regression: 0.7964601769911505
Recall of Logistic Regression: 0.9
F1 score of Logistic Regression: 0.8450704225352113


In [40]:
print("Precision of Decision Tree:",precision_score(y_test,y_pred_dt))
print("Recall of Decision Tree:",recall_score(y_test,y_pred_dt))
print("F1 score of Decision Tree:",f1_score(y_test,y_pred_dt))

Precision of Decision Tree: 0.9615384615384616
Recall of Decision Tree: 1.0
F1 score of Decision Tree: 0.9803921568627451


In [41]:
print("Precision of Random Forrest:",precision_score(y_test,y_pred_rf))
print("Recall of Random Forrest:",recall_score(y_test,y_pred_rf))
print("F1 score of Random Forrest:",f1_score(y_test,y_pred_rf))

Precision of Random Forrest: 1.0
Recall of Random Forrest: 1.0
F1 score of Random Forrest: 1.0


In [42]:
precision_score(y_test,y_pred_lr,average=None)

array([0.89130435, 0.79646018])

In [43]:
recall_score(y_test,y_pred_lr,average=None)

array([0.78095238, 0.9       ])

In [44]:
f1_score(y_test,y_pred_lr,average=None)

array([0.83248731, 0.84507042])