In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [50]:
df = pd.read_csv('covid_toy.csv')
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [51]:
from sklearn.model_selection import train_test_split
X_train ,X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'])

In [52]:
X_train

age  gender  fever   cough       city
58   23    Male   98.0  Strong     Mumbai
30   15    Male  101.0    Mild      Delhi
99   10  Female   98.0  Strong    Kolkata
77    8  Female  101.0    Mild    Kolkata
52   47  Female  100.0  Strong  Bangalore
..  ...     ...    ...     ...        ...
15   70    Male  103.0  Strong    Kolkata
50   19    Male  101.0    Mild      Delhi
26   19  Female  100.0    Mild    Kolkata
90   59  Female   99.0  Strong      Delhi
74   34  Female  104.0  Strong      Delhi

[75 rows x 5 columns]

In [53]:
X_test

age  gender  fever   cough       city
14   51    Male  104.0    Mild  Bangalore
11   65  Female   98.0    Mild     Mumbai
4    65  Female  101.0    Mild     Mumbai
94   79    Male    NaN  Strong    Kolkata
7    20  Female    NaN  Strong     Mumbai
64   42    Male  104.0    Mild     Mumbai
91   38    Male    NaN    Mild      Delhi
10   75  Female    NaN    Mild      Delhi
32   34  Female  101.0  Strong      Delhi
66   51    Male  104.0    Mild    Kolkata
33   26  Female   98.0    Mild    Kolkata
24   13  Female  100.0  Strong    Kolkata
92   82  Female  102.0  Strong    Kolkata
40   49  Female  102.0    Mild      Delhi
37   55    Male  100.0    Mild    Kolkata
68   54  Female  104.0  Strong    Kolkata
31   83    Male  103.0    Mild    Kolkata
88    5  Female  100.0    Mild    Kolkata
39   50  Female  103.0    Mild    Kolkata
25   23    Male    NaN    Mild     Mumbai
5    84  Female    NaN    Mild  Bangalore
79   48  Female  103.0    Mild    Kolkata
8    19  Female  100.0  Strong  Bangalore
97   20  Female  101.0    Mild  Bangalore
96   51  Female  101.0  Strong    Kolkata

# 1. Without column transformer

### simple imputer (fever)

In [54]:
from sklearn.impute import SimpleImputer

si = SimpleImputer()

X_train_fever =  si.fit_transform(X_train[['fever']])
X_test_fever =  si.transform(X_test[['fever']])
X_train_fever

array([[ 98.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [ 99.        ],
       [102.        ],
       [104.        ],
       [102.        ],
       [100.        ],
       [101.        ],
       [101.        ],
       [100.66197183],
       [ 98.        ],
       [104.        ],
       [ 99.        ],
       [103.        ],
       [ 98.        ],
       [100.        ],
       [102.        ],
       [100.66197183],
       [103.        ],
       [ 98.        ],
       [103.        ],
       [ 98.        ],
       [ 98.        ],
       [102.        ],
       [103.        ],
       [101.        ],
       [101.        ],
       [ 99.        ],
       [101.        ],
       [ 99.        ],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [103.        ],
       [100.66197183],
       [104.        ],
       [ 98.        ],
       [100

# Ordinnal Encoding

In [55]:
from sklearn.preprocessing import  OrdinalEncoder
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough=  oe.fit_transform(X_train[['cough']])
X_test_cough =  oe.transform(X_test[['cough']])
X_train_cough

array([[1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.]])

# OneHotEncoding

In [56]:
X_train['city'].value_counts()

city
Bangalore    26
Kolkata      20
Delhi        18
Mumbai       11
Name: count, dtype: int64

In [57]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False,drop='first')
X_train_genderCity =  ohe.fit_transform(X_train[['gender','city']])
X_test_genderCity =  ohe.transform(X_test[['gender','city']])
X_train_genderCity

C:\Users\HP TECHNOLOGY\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],


In [70]:
X_train_age =  X_train['age']
X_test_age =  X_test['age']
X_train_age = np.array(X_train_age).reshape(75,1)
X_test_age = np.array(X_test_age).reshape(25,1)

In [59]:
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [69]:
print(X_train_age.shape,X_train_genderCity.shape,X_train_fever.shape,X_train_cough.shape)
print(X_test_age.shape,X_test_genderCity.shape,X_test_fever.shape,X_test_cough.shape)

(75, 1) (75, 4) (75, 1) (75, 1)
(25,) (25, 4) (25, 1) (25, 1)


##### concat them

In [71]:
X_train_concat = np.concatenate((X_train_age,X_train_genderCity,X_train_fever,X_train_cough),axis=1)
X_test_concat = np.concatenate((X_test_age,X_test_genderCity,X_test_fever,X_test_cough),axis=1)

# Column Transformer

In [77]:
X_train ,X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'])

In [78]:
from sklearn.compose import ColumnTransformer

In [81]:
transformer = ColumnTransformer(transformers=[
    ('trf1',SimpleImputer(),['fever']),
    ('trf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('trf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [82]:
X_train_trf = transformer.fit_transform(X_train)
X_test_trf = transformer.transform(X_test)

C:\Users\HP TECHNOLOGY\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [83]:
X_train_trf

array([[103.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  46.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  54.        ],
       [102.        ,   1.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  20.        ],
       [100.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [100.85507246,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  79.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  81.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  64.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  11.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.    