In [1]:
import numpy as np
from sklearn.datasets import load_diabetes

In [2]:
X,y = load_diabetes(return_X_y=True)

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [5]:
reg = LinearRegression()
reg.fit(X_train, y_train)
y_pred = reg.predict(X_test)
r2_score(y_test, y_pred)

0.4399338661568968

In [6]:
reg.intercept_, reg.coef_

(151.88331005254167,
 array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
        -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
         861.12700152,   52.42112238]))

# Ownclass

![A descriptive alt text](linear_regression.png)


In [16]:
class MultipleLinearRegression:
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        
    def fit(self,X_train,y_train):
        # insert 1 at 0th column
        X_train = np.insert(X_train,0,1,axis=1)
        
        beta = np.linalg.inv(np.dot(X_train.T, X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = beta[0]
        self.coef_ = beta[1:]
        
    def predict(self,X_test):
        return  self.intercept_ + np.dot(X_test, self.coef_)
    

In [17]:
lr = MultipleLinearRegression()

In [18]:
lr.fit(X_train, y_train)

In [19]:
y_pred = lr.predict(X_test)

In [20]:
r2_score(y_test,y_pred)

0.4399338661568969

In [21]:
lr.intercept_, lr.coef_

(151.88331005254167,
 array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
        -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
         861.12700152,   52.42112238]))

###### some manual calculation

In [10]:
X_train1 = np.insert(X_train,0,1,axis=1)
X_train1

array([[ 1.        , -0.00188202, -0.04464164, ..., -0.03949338,
        -0.06291688,  0.04034337],
       [ 1.        , -0.00914709, -0.04464164, ..., -0.03949338,
         0.01703607, -0.0052198 ],
       [ 1.        ,  0.02354575,  0.05068012, ..., -0.03949338,
        -0.09643495, -0.01764613],
       ...,
       [ 1.        ,  0.06350368,  0.05068012, ..., -0.00259226,
         0.08449153, -0.01764613],
       [ 1.        , -0.05273755,  0.05068012, ...,  0.1081111 ,
         0.03606033, -0.04249877],
       [ 1.        ,  0.00175052,  0.05068012, ...,  0.1081111 ,
         0.06898589,  0.12732762]])

In [11]:
beta = np.linalg.inv(np.dot(X_train.T, X_train)).dot(X_train.T).dot(y_train)
beta

array([  11.10014699, -245.28091353,  381.8791825 ,  369.55714342,
       -918.39620672,  601.65165138,  131.74485109, -167.02405018,
       1055.08912682,   54.60659094])